# Generated by Django 3.1 on 2020-08-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shopinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopinfo',
            options={'verbose_name': 'Заголовок каталога', 'verbose_name_plural': 'Заголовок каталога'},
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядковый номер'),
        ),
    ]
