# Generated by Django 3.1 on 2020-08-23 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200824_0152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('order',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
