# Generated by Django 3.1 on 2020-08-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200824_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='neworder',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
