# Generated by Django 3.1 on 2020-08-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_neworder_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='neworder',
            name='product',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название товара'),
        ),
    ]
