# Generated by Django 3.1 on 2020-08-23 14:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(max_length=1000, verbose_name='Описание')),
                ('icon', models.CharField(help_text='https://fontawesome.com/icons?d=gallery', max_length=255, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Блок с иконками',
                'verbose_name_plural': 'Блоки с иконками',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(unique=True, verbose_name='Подряковый номер')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок слайда')),
                ('sub_title', models.CharField(blank=True, max_length=150, verbose_name='Текст надо заголовом (необязательно)')),
                ('image', models.ImageField(help_text='Желательно оптимизировать на сайте https://tinypng.com/', upload_to=None, verbose_name='Картинка')),
                ('btn_text', models.CharField(max_length=100, verbose_name='Текст - приглашение')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='https://fontawesome.com/icons?d=gallery', max_length=255, verbose_name='Иконка')),
                ('url', models.URLField(verbose_name='Полная ссылка на страницу компании в соц сети')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('icon', models.CharField(max_length=255, verbose_name='Должность')),
                ('image', models.ImageField(help_text='Желательно оптимизировать на сайте https://tinypng.com/', upload_to=None, verbose_name='Фото (в книжном формате)')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок страницы с контактами')),
                ('sub_title', models.TextField(max_length=1000, verbose_name='Текст под заголовком')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('map_iframe', models.TextField(verbose_name='Код с Google карты')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('whatsapp', models.CharField(max_length=30, verbose_name='Whatsapp (без 8, пробелов и символов)')),
                ('social', models.ManyToManyField(to='main.Social', verbose_name='Соцсети')),
            ],
            options={
                'verbose_name': 'Информация о компании',
                'verbose_name_plural': 'Информация о компании',
            },
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='название файла должно быть logo', upload_to='logo/', verbose_name='Картинка')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('sub_title', models.TextField(max_length=1000, verbose_name='Текст под заголовком')),
                ('service_title', models.CharField(max_length=100, verbose_name='Заголовок блока с иконками')),
                ('info_title', models.CharField(max_length=255, verbose_name='Заголовок блока с информацией')),
                ('info', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Блок жюри - описание')),
                ('team_title', models.CharField(max_length=255, verbose_name='Заголовок блока с командой')),
                ('services', models.ManyToManyField(to='main.Service', verbose_name='Преимущества или сервис')),
                ('team', models.ManyToManyField(to='main.Team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Информация о компании',
                'verbose_name_plural': 'Информация о компании',
            },
        ),
    ]
