# Generated by Django 3.1 on 2020-08-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200824_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='services',
        ),
    ]
