# Generated by Django 3.1 on 2020-08-24 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='team',
        ),
    ]
