# Generated by Django 3.1 on 2020-08-25 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_telegrambot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramBot',
        ),
    ]
